name: Spring Boot Kotlin CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Notify dev
        run: |
          echo "Application deployed! Open http://localhost:8080/orders"
          
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build & test with Gradle
        run: ./gradlew clean build
